server.port=8081

spring.application.name=spring-webflux-cpu

reactor.netty.ioWorkerCount=0
reactor.netty.ioSelectCount=0

workload.cpu.sha256.iterations=25000

logging.level.root=WARN
logging.level.com.tcc.concurrency=WARN
