server.port=8081

spring.application.name=spring-webflux-io

#spring.r2dbc.url=r2dbc:postgresql://localhost:5432/testdb
#spring.r2dbc.username=testuser
#spring.r2dbc.password=testpass

#spring.r2dbc.pool.initial-size=50
#spring.r2dbc.pool.max-size=50
#spring.r2dbc.pool.max-acquire-time=30s
#spring.r2dbc.pool.max-idle-time=10m
#spring.r2dbc.pool.max-life-time=30m

workload.io.file.path=/tmp/benchmark-webflux.log
workload.io.file.payload-size-bytes=10240

downstream.url=http://localhost:9090
downstream.http.pool.max-connections=2000
downstream.http.pool.pending-acquire-max-count=5000
downstream.http.timeout.connect-ms=5000
downstream.http.timeout.response-ms=30000

logging.level.root=WARN
logging.level.com.tcc.concurrency=WARN
logging.level.io.r2dbc=WARN
