server.port=8080
#server.tomcat.threads.max=12
#server.tomcat.threads.min-spare=12
#server.tomcat.accept-count=100
#server.tomcat.max-connections=8192

spring.application.name=spring-mvc-cpu

workload.cpu.sha256.iterations=25000

logging.level.root=WARN
logging.level.com.tcc.concurrency=WARN
